#!/bin/bash
# List installed packages from repo
if [ "$#" -lt "1" ] ;then
  pacman -Qq | sort > ~/installedPacages.txt
elif [ "$#" -gt "2" ]; then
    echo "Invalid number of arguments"
    echo "Usage: $0 <repo>"
    exit
elif [ "$#" -eq "1" ];then
  pacman -Slq $1 | sort > insRepoPacages.txt
fi

#pacman -Qq | sort > tmp_installed.txt
#pacman -Slq $1 | sort > tmp_repo.txt
