#!/bin/bash
dir=$(pwd)

if [ -f $dir/main.c ];then
cd $dir && clang main.c -o main && ./main
else
read -p "Default not found enter file name :"
  if [ -f $dir/$REPLY ];then
  cd $dir && clang $REPLY -o main && ./main
  else
  printf "file not found\n"
  fi
fi


