#!/bin/bash

dir=$(pwd)

if [ -f $dir/main.rs ];then
cd $dir && rustc main.rs -o main -W -O2 && ./main
else
read -p "Default not found enter file name :"
  if [ -f $dir/$REPLY ];then
  cd $dir && rustc $REPLY -o main -W -O2 && ./main
  else
  printf "file not found\n"
  fi
fi


