#!/bin/bash 
read -p "Git message: "
area=$(pwd)
printf "do you want to push? [Y/n]: "
read gitAns

if [ $gitAns = "N" ] || [ $gitAns = "n" ];then
cd $area && git add . && git commit -m "$REPLY";
else
cd $area && git add . && git commit -m "$REPLY" && git push;
fi
