#!/bin/bash
counte=$((0))
counts=$((0))

function delete_obj(){
  if [ -f $(pwd)/$1 ];then
    printf "$1 found\n"
    cd $(pwd) && rm $1 
  counts=$((counts+1))
else
  printf "$1 not found\n"
  counte=$((counte+1))
fi
}

delete_obj "main"
delete_obj "a.out"
delete_obj "main_program"
delete_obj "a"
delete_obj "run"
printf "done,\n test-cases: succesful:$counts unsuccesful:$counte\n"
