#!/bin/bash
DIR=$(pwd)
function runasm(){
cd $DIR && nasm -f elf64 $1 -o main.o && ld main.o -o main && ./main
}

if [ -f $DIR/main.asm ];then
  runasm "main.asm"
else
  echo "Default main.asm not found"
  read -p "Enter file name: "
  if [ -f $DIR/$REPLY ];then
    runasm "$REPLY"
  else
    echo "file not found, program terminated"
  fi
fi


