#!/bin/bash

dir=$(pwd)

if [ -f $dir/main.cpp ];then
cd $dir && clang++ main.cpp -o main -W -O2 && ./main
else
read -p "Default not found enter file name :"
  if [ -f $dir/$REPLY ];then
  cd $dir && clang++ $REPLY -o main -W -O2 && ./main
  else
  printf "file not found\n"
  fi
fi


