#!/bin/bash
# sometimes $HOME DOESNT WORK
#i dunno what the fuck this code is 
DIR=$(pwd)
function makef(){
    echo '# personal executables folder' >> $HOME/$1
    echo "export PATH='\$PATH:$DIR/../'" >> $HOME/$1
}
echo "what is your shell file [ .bashrc or .zshrc ]? default: .zshrc : "
read shell_name
if [ -f "$HOME/$shell_name" ];then
  makef $shell_name
else
  echo "file not found"
  if [ -f "$HOME/.zshrc" ];then
      echo "zshrc found, placing there" && makef ".zshrc" || echo "Error occured whiles placing in .zshrc"
     else
      echo "zshrc not found, running on .bashrc"
      [ -f "$HOME/.bashrc" ] && makef ".bashrc" || echo "Could not find .bashrc"
  fi
fi
