#!/bin/bash

<<COMMENTS
this executable is to add this current folder to path so the 
executables in this folder can be launched anywhere without
needing the full path
by default it echoes into .zshrc
if you use any other eg: .bashrc, .bashprofile, etc make changes
COMMENTS
#sometimes $HOME DOESNT WORK
DIR=$(pwd)
function make(){
echo "#personal executables folder" >> $HOME/$1
echo "export PATH='\$PATH:$DIR'" >> $HOME/$1
source $HOME/$1
}
read -p "what is your shell file? default: .zshrc : "
if [ -f $HOME/$REPLY ];then
  make "$REPLY"
else
  echo "file not found"
  if [ -f $HOME/.zshrc ];then
    echo "zshrc found, placing there"
    make ".zshrc"
  else
    echo "zshrc not found, program terminated"
  fi
fi
